worker_processes 1;

events {
  worker_connections 1024;
}

http {
  upstream jetty_app {
    server 127.0.0.1:8080;
    keepalive 32;
  }

  server {
    listen 80;
    server_name localhost;

    charset utf-8;

    location /public/ {
      alias "/home/remi/Code/IdeaProjects/MAI/ProgramEngineering/lab2/public/";
      autoindex on;
    }

    location /jetty/ {
      proxy_pass http://jetty_app/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}