worker_processes 1;

events {
  worker_connections 1024;
}

http {
  upstream spring_app {
    server 127.0.0.1:49080;
    keepalive 32;
  }

  server {
    listen 80;
    server_name localhost;

    charset utf-8;

    location /web/ {

    }

    location /api/ {
      proxy_pass http://spring_app/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}